### ISSUE TITLE
the treelist not work for Hierarchical Structure

### ISSUE THREAD

**Issue by dljzc** [pikhovkin/dash-devextreme#2]
![image](https://user-images.githubusercontent.com/58949406/98052179-6b731d80-1e2d-11eb-882d-f8eb30f937e7.png)

the Hierarchical Structure is not working? can you help me?

**Comment by pikhovkin** [comment]
Have you watched [advanced_usage.py](https://github.com/pikhovkin/dash-devextreme/blob/master/advanced_usage.py#L123)?

**Comment by dljzc** [comment]
hi,

i found the issue which is i didn't use CSS, other questions, in editing
how to use the "add", "Save" button?


Sergei Pikhovkin <notifications@github.com> 于2020年11月5日周四 下午4:59写道：

**Comment by pikhovkin** [comment]
```python
...
row_editing = {
    'mode': 'row',
    'allowAdding': True,
    'allowUpdating': True,
    'allowDeleting': True,
}
...
ddx.TreeList(dataSource=data, columns=columns, keyExpr='id', parentIdExpr='parent_id', editing=row_editing),
...
```

**Comment by pikhovkin** [comment]
@dljzc  Add each question as a separate issue
