### ISSUE TITLE
Collapse Grouping not working on DataGrid component

### ISSUE THREAD

**Issue by edh88** [pikhovkin/dash-devextreme#3]
Thanks for this great component.  I have been able to add the column grouping functionality but do not seem to be able to get the row expand/collapse functionality to work.

![image](https://user-images.githubusercontent.com/43501777/107487304-f75bba80-6b7d-11eb-8fc1-99a805f67531.png)

Current code is as follows (although I have tried various combinations in the grouping variable);

```python
app.layout = html.Div([
    ddx.DataGrid(dataSource=dataSource,
                 filterRow={'visible':True},
                 headerFilter={'visible':True},
                 grouping={'allowCollapsing':True,'autoExpandAll':True,'expandMode':'rowClick'},
                 columnChooser={'enabled':True,'mode':"select"},
                 groupPanel={'visible':True,'allowColumnDragging':True},
                 export={'enabled':True,'fileName':'Positions'}),
])

if __name__ == '__main__':
    app.run_server(debug=True)

```

**Comment by pikhovkin** [comment]
What version are you using?

**Comment by edh88** [comment]
I was using 0.11.3 but after your message I have just updated to the latest version (0.12.4) and it works perfectly.  I had not thought to look for an update as github seemed to show the repo hadn't been updated in a while!

Apologies, but thanks for the help!
