### ISSUE TITLE
Filter Builder - Correct Configuration

### ISSUE THREAD

**Issue by edh88** [pikhovkin/dash-devextreme#4]
Could you please advise how to correctly configure the Filter Builder Popup

I am able to enable this feature, and can see it is having the desired effect on the underlying DataGrid, but once the popup is opened, clicking OK or Cancel doesn't permanent close box (it opens back up again)

![image](https://user-images.githubusercontent.com/43501777/107492239-1a896880-6b84-11eb-9781-2dc45560b534.png)

**Comment by pikhovkin** [comment]
What version are you using?

**Comment by edh88** [comment]
I was using 0.11.3 but after your message I have just updated to the latest version (0.12.4) and it works perfectly.  I had not thought to look for an update as github seemed to show the repo hadn't been updated in a while!

Apologies, but thanks for the help!
